### ISSUE TITLE
triple tip worked, but only last tip got emojis.

### ISSUE THREAD

**Issue by coranos** [bbedward/Graham_Nano_Tip_Bot#26]
i did .ban, saw no response emojis. 
did .ban again, no response emojis. 
did .ban a third time, only the third one got check marks.
but all three went through.

I deleted the posts since they were spam in the tahiti channel. I'm not sure if deleting them had anything to do with it, as I waited a while (2 minutes) before deleting them.

**Comment by bbedward** [comment]
This happens when the node is non-responsive.

There's something like a 5 minute timeout , so if it takes 3 minutes to get a node response for example the tip still goes through. If it takes > 5 minutes then the RPC call times out and tip doesn't go through.

Will probably solve in Graham 4.0 by reducing the timeout for RPC calls that should be fast (like balance). And adding feedback when a request times out so you know the tip won't be processed.

**Comment by bbedward** [comment]
Bot responds immediately when tip is successful in v4

https://github.com/bbedward/Graham_Nano_Tip_Bot/tree/v4

No response emojis in v4 could be related to discord APIs being offline, having issues, etc. - but will consider those an edge case we can't do anything about.
